/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KOMPUTER
 */
public class PanelFrame extends javax.swing.JFrame {

    /**
     * Creates new form PanelFrame
     */
    public PanelFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWyswietlaczy1 = new PanelWyswietlaczy();
        panelWyswietlaczy2 = new PanelWyswietlaczy();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelWyswietlaczy1.setAktualnyNapis("8 bF");
        panelWyswietlaczy1.setCzyRysowacRamke(java.lang.Boolean.FALSE);
        panelWyswietlaczy1.setCzyWskazywacNaWszystkieWyswietlacze(java.lang.Boolean.FALSE);
        panelWyswietlaczy1.setIloscWyswietlaczy(new java.lang.Integer(4));
        panelWyswietlaczy1.setKolorSegmentuWyswietlacza(java.awt.Color.cyan);
        panelWyswietlaczy1.setKolorTla(java.awt.Color.darkGray);
        panelWyswietlaczy1.setKolorTlaWyswietlacza(java.awt.Color.red);
        panelWyswietlaczy1.setKolorWygaszonegoSegmentuWyswietlacza(java.awt.Color.pink);
        panelWyswietlaczy1.setSzerokoscWyswietlaczy(new java.lang.Integer(72));
        panelWyswietlaczy1.setWskazywanyWyswietlacz(new java.lang.Integer(3));
        panelWyswietlaczy1.setWysokoscWyswietlaczy(new java.lang.Integer(142));

        panelWyswietlaczy2.setAktualnyNapis("124Fb2");
        panelWyswietlaczy2.setCzyWskazywacNaWszystkieWyswietlacze(java.lang.Boolean.FALSE);
        panelWyswietlaczy2.setIloscRzedow(new java.lang.Integer(2));
        panelWyswietlaczy2.setIloscWyswietlaczy(new java.lang.Integer(6));
        panelWyswietlaczy2.setKolorSegmentuWyswietlacza(java.awt.Color.black);
        panelWyswietlaczy2.setKolorTlaWyswietlacza(java.awt.Color.green);
        panelWyswietlaczy2.setSzerokoscPionowaMiedzyWyswietlaczami(new java.lang.Integer(80));
        panelWyswietlaczy2.setSzerokoscPoziomaMiedzyWyswietlaczami(new java.lang.Integer(70));
        panelWyswietlaczy2.setSzerokoscWyswietlaczy(new java.lang.Integer(124));
        panelWyswietlaczy2.setWskazywanyWyswietlacz(new java.lang.Integer(5));
        panelWyswietlaczy2.setWysokoscWyswietlaczy(new java.lang.Integer(244));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panelWyswietlaczy1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(panelWyswietlaczy2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelWyswietlaczy1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelWyswietlaczy2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelWyswietlaczy panelWyswietlaczy1;
    private PanelWyswietlaczy panelWyswietlaczy2;
    // End of variables declaration//GEN-END:variables
}
