/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KOMPUTER
 */
public class WyswietlaczFrame extends javax.swing.JFrame {

    /**
     * Creates new form WyswietlaczFrame
     */
    public WyswietlaczFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wyswietlacz7seg1 = new Wyswietlacz7seg();
        wyswietlacz7seg2 = new Wyswietlacz7seg();
        wyswietlacz7seg3 = new Wyswietlacz7seg();
        wyswietlacz7seg4 = new Wyswietlacz7seg();
        wyswietlacz7seg5 = new Wyswietlacz7seg();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wyswietlacz7seg1.setGruboscRamki(new java.lang.Integer(4));
        wyswietlacz7seg1.setStan(new java.lang.Character('9'));
        wyswietlacz7seg1.setSzerokoscSegmentu(new java.lang.Integer(16));

        javax.swing.GroupLayout wyswietlacz7seg1Layout = new javax.swing.GroupLayout(wyswietlacz7seg1);
        wyswietlacz7seg1.setLayout(wyswietlacz7seg1Layout);
        wyswietlacz7seg1Layout.setHorizontalGroup(
            wyswietlacz7seg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        wyswietlacz7seg1Layout.setVerticalGroup(
            wyswietlacz7seg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        wyswietlacz7seg2.setCzySkalowalny(java.lang.Boolean.FALSE);
        wyswietlacz7seg2.setKolorPalacegoSieSegmentu(java.awt.Color.green);
        wyswietlacz7seg2.setKolorTla(java.awt.Color.white);
        wyswietlacz7seg2.setModyfikatorWielkosci(new java.lang.Double(0.5));
        wyswietlacz7seg2.setStan(new java.lang.Character('2'));

        javax.swing.GroupLayout wyswietlacz7seg2Layout = new javax.swing.GroupLayout(wyswietlacz7seg2);
        wyswietlacz7seg2.setLayout(wyswietlacz7seg2Layout);
        wyswietlacz7seg2Layout.setHorizontalGroup(
            wyswietlacz7seg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        wyswietlacz7seg2Layout.setVerticalGroup(
            wyswietlacz7seg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        wyswietlacz7seg3.setCzySkalowalny(java.lang.Boolean.FALSE);
        wyswietlacz7seg3.setGruboscRamki(new java.lang.Integer(9));
        wyswietlacz7seg3.setKolorPalacegoSieSegmentu(java.awt.Color.black);
        wyswietlacz7seg3.setKolorTla(java.awt.Color.red);
        wyswietlacz7seg3.setModyfikatorWielkosci(new java.lang.Double(0.5));
        wyswietlacz7seg3.setStan(new java.lang.Character('E'));

        javax.swing.GroupLayout wyswietlacz7seg3Layout = new javax.swing.GroupLayout(wyswietlacz7seg3);
        wyswietlacz7seg3.setLayout(wyswietlacz7seg3Layout);
        wyswietlacz7seg3Layout.setHorizontalGroup(
            wyswietlacz7seg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        wyswietlacz7seg3Layout.setVerticalGroup(
            wyswietlacz7seg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        wyswietlacz7seg4.setCzySkalowalny(java.lang.Boolean.FALSE);
        wyswietlacz7seg4.setKolorPalacegoSieSegmentu(java.awt.Color.blue);
        wyswietlacz7seg4.setKolorTla(java.awt.Color.red);
        wyswietlacz7seg4.setKolorWylaczonegoSegmentu(java.awt.Color.orange);
        wyswietlacz7seg4.setModyfikatorWielkosci(new java.lang.Double(0.5));
        wyswietlacz7seg4.setStan(new java.lang.Character('b'));

        javax.swing.GroupLayout wyswietlacz7seg4Layout = new javax.swing.GroupLayout(wyswietlacz7seg4);
        wyswietlacz7seg4.setLayout(wyswietlacz7seg4Layout);
        wyswietlacz7seg4Layout.setHorizontalGroup(
            wyswietlacz7seg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        wyswietlacz7seg4Layout.setVerticalGroup(
            wyswietlacz7seg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        wyswietlacz7seg5.setGruboscRamki(new java.lang.Integer(3));
        wyswietlacz7seg5.setKolorPalacegoSieSegmentu(java.awt.Color.white);
        wyswietlacz7seg5.setKolorTla(java.awt.Color.black);
        wyswietlacz7seg5.setStan(new java.lang.Character('2'));
        wyswietlacz7seg5.setSzerokoscSegmentu(new java.lang.Integer(3));

        javax.swing.GroupLayout wyswietlacz7seg5Layout = new javax.swing.GroupLayout(wyswietlacz7seg5);
        wyswietlacz7seg5.setLayout(wyswietlacz7seg5Layout);
        wyswietlacz7seg5Layout.setHorizontalGroup(
            wyswietlacz7seg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        wyswietlacz7seg5Layout.setVerticalGroup(
            wyswietlacz7seg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wyswietlacz7seg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wyswietlacz7seg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(wyswietlacz7seg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(wyswietlacz7seg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(wyswietlacz7seg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wyswietlacz7seg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wyswietlacz7seg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wyswietlacz7seg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wyswietlacz7seg5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wyswietlacz7seg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WyswietlaczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WyswietlaczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WyswietlaczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WyswietlaczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WyswietlaczFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Wyswietlacz7seg wyswietlacz7seg1;
    private Wyswietlacz7seg wyswietlacz7seg2;
    private Wyswietlacz7seg wyswietlacz7seg3;
    private Wyswietlacz7seg wyswietlacz7seg4;
    private Wyswietlacz7seg wyswietlacz7seg5;
    // End of variables declaration//GEN-END:variables
}
